extends Node

const Ability := {
	"Move": "Permite mover para um rank dentro do alcance.",
	"Pass": "Pula o seu turno.",
	"OccultEndowment": "Requer si: HP >20%%.\nRecupera 33% HP do alvo, e causa 20% do HP como Dano ao usuário.\nDano reduzido por 100% quando usuário tem Favor Profano.",
	"CrownOfThorns": "O alvo recebe 20% aumento de Dano e +1 Velocidade por 3 turnos.",
	"FatesShield": "Cooldown: 2 turno\nO alvo recebe 20% Proteção e 2 Regeneração por 3 turnos.",
	"EldritchDevotion": "Cooldown: 1 turno\nCausa 4-5 Dano, o alvo causa 20% Dano reduzido por 2 turnos e recebe Exposto.",
	"SoulPenance": "Causa 6-8 Dano ao alvo, se estiver Exposto o usuário recebe Favor Profano por 2 turnos.",
	"Defibrilate": "Cooldown: 3 turnos\nO alvo recebe 3 Regeneração e +1 Velocidade por 2 turnos, se HP <30% Recebe +50% Proteção por 1 turno.",
	"ShockingDiscovery": "Cooldown: 1 turno\nCausa 5-9 Dano ao alvo e recebe Exposto.",
	"MagnetizeElectrons": "Causa 6-11 Dano ao alvo e Puxa 2 ranks.",
	"UnstableCore": "Cooldown: 1 turno\nCausa 4-6 Dano ao alvo e aplica 3 Queimadura por 3 turnos.",
	"Accelerare": "Cooldown: 2 turnos\nO alvo recebe +20% Esquiva e +2 Velocidade por 2 turnos.",
	"DarkLunge": "Causa 6-14 Dano ao alvo, +35% Dano se o alvo estiver Sangrando.\nAnda 2 ranks para frente.",
	"RazorClaws": "Causa 4-8 Dano aos alvos, aplica 2 Sangramento por 2 turnos e -10% Resistência Sang. por 3 turnos.\nAnda 1 rank para frente.",
	"SpiritBreak": "Causa 6-14 Dano ao alvo, +20% Dano se o alvo estiver Sangrando.\nAnda 1 rank para trás.",
	"DarkDomain": "Cooldown: 2 turnos\nO usuário recebe +15% Chance Crítico e +2 Velocidade por 3 turnos.",
	"Overlord": "",
	"RunicBlade": "Causa 7-9 Dano ao alvo, +50% Dano se Exposto.",
	"AncientRebuke": "Causa 5-7 Dano aos alvos e aplica 2 Queimadura por 3 turnos.",
	"BlessedBlade": "Causa 5-6 Dano aos alvos, o usuário cura 10% HP se algum estiver Exposto.",
	"LastStand": "Cooldown: 3 turnos\nO usuário recebe +20% Proteção e 3 Regeneração por 2 turnos, e recebe Provocação por 3 turnos.",
	"Lover": "",
	"RootsEdge": "Causa 7-11 Dano ao alvo e aplica 1 Sangramento por 3 turnos.",
	"BuriedStrike": "Causa 7-11 dano ao alvo e aplica Exposto.",
	"Twister": "Causa 5-8 Dano ao alvo e Empurra 1 rank, aplica -3 Velocidade por 3 turnos se Exposto.\nAnda 1 rank para frente.",
	"NaturalBounty": "Cooldown: 2 turnos\nO usuário Recebe 30% Proteção por 3 turnos e o alvo recebe 10% Proteção por 2 turnos.",
	"Druid": "",
	"HighShot": "Causa 6-14 Dano ao alvo, +25% Dano e +10 Chance Crítico se Exposto.",
	"ArrowsFlight": "Causa 4-8 Dano aos alvos e aplica -1 Velocidade por 3 turnos.",
	"TakeAim": "Cooldown: 2 turnos\nO usuário recebe +2 Velocidade por 3 turnos, e o alvo é Exposto.",
	"PlanB": "Causa 6-14 Dano ao alvo e ignora 15% Proteção.",
	"WildArrow": "",
	"DeadlyFlourish": "Causa 8-14 Dano ao alvo, +100% Chance Crítico e Empurra 1 rank se Exposto.\nAnda 3 ranks para trás.",
	"LeadStep": "Causa 7-12 Dano ao alvo.\nO usuário recebe +3 Velocidade por 1 turnos e Anda 1 rank para frente.",
	"VoidWaltz": "Causa 6-10 Dano ao alvo, Puxa 1 rank e aplica Exposto.\nAnda 1 rank para frente.",
	"DisciplinedBeast": "Causa 2-3 Dano aos alvos e aplica 2 Peste por 3 turnos.",
	"Follower": "",
	"TheScorcher": "Causa 7-12 Dano ao alvo, causa +2 Dano se o alvo estiver Queimando e o usuário recebe OnFire.",
	"Buckshot": "Causa 4-7 Dano ao alvo.\nAnda 1 rank para trás.",
	"Smokestack": "Aplica 1 Queimadura e -10% Acerto ao alvos.",
	"ExplosiveRound": "Requer si: OnFire\nCausa 9-16 Dano ao alvo e aplica 5 Queimadura por 3 turnos.\nRemove OnFire de si.",
	"FireUp": "Requer si: OnFire\nAplica +30% Dano e +15% Esquiva ao alvo por 2 turnos.\nRemove OnFire de si.",
	"PrayerOfComfort": "Cooldown: 1\nRecupera 10% HP do alvo.\nSe 2 Favor Divino +10% Cura.\nSe 3 Favor Divino +15% Cura.",
	"Skill": "",
	"Skilll": "",
	"Skillll": "",
	"Priest": "",
	"Hotmeal": "Cooldown: 2 turnos\nO alvo recebe 2 Regeneração por 3 turnos.",
	"DeadlyReactant": "Causa 3-6 Dano ao alvo e aplica 3 Peste por 3 turnos.\nO usuário aplica +25% Regeneração por 3 turnos.",
	"SecretIngredient": "Causa 2-4 Dano aos alvos e aplica 2 Peste por 3 turnos.\nO usuário aplica +25% Regeneração por 3 turnos.",
	"AromaticHerbs": "Cooldown: 2 turnos\nO alvo recebe 1 Regeneração por 2 turnos e é curado de Sangramento, Queimadura e Peste.",
	"Chef": "",
	"Punish": "",
	"RainOfSorrow": "",
	"Suffer": "",
	"Exsanguinate": "",
	"Reclaim": "",
	"": "",
}
